version: '3.8'

services:
  # Service pour l'application
  blue_window:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/my_database
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db
      - phpmyadmin
    command: ["npm", "run", "dev"]

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
    driver: local
